### ISSUE TITLE
Improve note syndication

### ISSUE THREAD

**Issue by MarcL** [MarcL/marclittlemore.com#319]
```[tasklist]
### Tasks
- [ ] Chunk messages to allow sending threads: https://www.npmjs.com/package/textchunk
- [ ] Allow upload of images
- [ ] Add a link back to original post URL as part of the message
```
